
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 12 22:57:54 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 20;
  public static final int MOD = 22;
  public static final int READ = 2;
  public static final int IDENT = 28;
  public static final int PLUS = 19;
  public static final int RBRACE = 7;
  public static final int RPAREN = 15;
  public static final int EQUAL = 11;
  public static final int SEMI = 10;
  public static final int PLUS_PLUS = 16;
  public static final int RETURN = 24;
  public static final int NUM_CONST = 25;
  public static final int BOOL_CONST = 27;
  public static final int LBRACKET = 12;
  public static final int LPAREN = 14;
  public static final int LBRACE = 6;
  public static final int RBRACKET = 13;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int DIV = 21;
  public static final int PROG = 5;
  public static final int MINUS = 18;
  public static final int CONST = 8;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int NEW = 23;
  public static final int MINUS_MINUS = 17;
  public static final int VOID = 4;
  public static final int CHAR_CONST = 26;
}

